"""Clean schema reset

Revision ID: 7c30c7527695
Revises: 
Create Date: 2025-06-14 11:39:20.549977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c30c7527695'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_survey_responses_id'), table_name='survey_responses')
    op.drop_table('survey_responses')
    op.drop_index(op.f('ix_background_id'), table_name='background')
    op.drop_table('background')
    op.add_column('demographics', sa.Column('identity', sa.Text(), nullable=False, server_default='[]'))
    op.drop_column('demographics', 'race_ethnicity')
    op.drop_column('demographics', 'gender')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('demographics', sa.Column('gender', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('demographics', sa.Column('race_ethnicity', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('demographics', 'identity')
    op.create_table('background',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('experience', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('technologies_used', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('background_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('background_pkey'))
    )
    op.create_index(op.f('ix_background_id'), 'background', ['id'], unique=False)
    op.create_table('survey_responses',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('trustworthy', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('will_use_again', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ease_of_use', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('liked_thing', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('disliked_thing', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('tone_feedback', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('additional_comments', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('survey_responses_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('survey_responses_pkey'))
    )
    op.create_index(op.f('ix_survey_responses_id'), 'survey_responses', ['id'], unique=False)
    # ### end Alembic commands ###
