"""Initial clean migration with identity1 and identity2

Revision ID: 9dcb40d8818f
Revises: 
Create Date: 2025-06-27 14:34:09.308014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9dcb40d8818f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('demographics', sa.Column('identity1', sa.Text(), nullable=True))
    op.add_column('demographics', sa.Column('identity2', sa.Text(), nullable=True))
    op.drop_column('demographics', 'identity')
    op.drop_column('demographics', 'consent1')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('demographics', sa.Column('consent1', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('demographics', sa.Column('identity', sa.TEXT(), server_default=sa.text("'[]'::text"), autoincrement=False, nullable=False))
    op.drop_column('demographics', 'identity2')
    op.drop_column('demographics', 'identity1')
    # ### end Alembic commands ###
